version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd todo-service
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - todo-service/target/todo-service:jar:0.0.1-SNAPSHOT.jar